# Generated by Django 2.2.6 on 2021-07-17 19:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0006_auto_20210716_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='confirmation_code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='User', error_messages={'unique': 'Пользователь с таким никнеймом уже существует.'}, help_text='Обязательное поле! 150 символов или меньше. Буквы, цифры и @ /./+/-/_', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='никнейм'),
            preserve_default=False,
        ),
    ]
