# Generated by Django 2.2.6 on 2021-07-21 18:10

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0007_auto_20210717_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='9393', max_length=128, verbose_name='confirmation_code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким никнеймом уже существует.'}, help_text='Обязательное поле! 150 символов или меньше. Буквы, цифры и @ /./+/-/_', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='никнейм'),
        ),
    ]
